spring:
  application:
    name: peuteu
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:peuteu
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8181