jwt:
  prefix: "Bearer "
  claim: user
  secret: z9XVyW6fUclUWkHKspICWw

  access:
    age: 1800 # 30분
    header: Authorization
    subject: accessToken

  refresh:
    age: 1209600 # 14일 (60 * 60 * 24 * 14)
    minAgeInDay: 14
    subject: refreshToken