spring:
  application:
    name: peuteu

  profiles:
    active: local
    default: local
    group:
      local: local
      release: release
    include: jwt

  sql:
    init:
      mode: always

server:
  port: 8181