spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:peuteu
    url: jdbc:h2:file:C:/Dev/intellij-workspace/peuteu/peuteu
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true